# Generated by Django 5.0.6 on 2024-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('attempts_allowed', models.IntegerField()),
                ('feedback_options', models.TextField()),
            ],
        ),
    ]
